
services:
  backend:
    build: ./backend
    container_name: rag_platform_backend
    ports:
      - "5001:5000"
    env_file:
      - ./backend/.env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - rag_network

  frontend:
    build: ./frontend
    container_name: rag_platform_frontend
    ports:
      - "5173:5173"
    networks:
      - rag_network
    depends_on:
      - backend

networks:
  rag_network:
    driver: bridge
