# This version of the docker-compose.yml file is for LOCAL DEVELOPMENT.
# It uses the 'build' directive to create new images from your local Dockerfiles.
# Use this on your local machine to build and push images to ECR.


services:
  backend:
    # Tells Docker Compose to build an image using the Dockerfile in the './backend' directory
    build: ./backend
    # This is the name the image will have after being built.
    # It must match the image name used in your deployment docker-compose.yml file.
    image: 235639741719.dkr.ecr.us-east-2.amazonaws.com/my-chat-app/backend:latest
    container_name: rag_platform_backend_dev
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    networks:
      - rag_network

  frontend:
    # Tells Docker Compose to build an image using the Dockerfile in the './frontend' directory
    build: ./frontend
    # This is the name the image will have after being built.
    image: 235639741719.dkr.ecr.us-east-2.amazonaws.com/my-chat-app/frontend:latest
    container_name: rag_platform_frontend_dev
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge