# Stage 1: Builder Stage - Install dependencies
# Use a specific, stable Python version as the base image for building
FROM python:3.11-slim

# Set the working directory inside this builder container
WORKDIR /app

# Copy only the requirements file first.
# This step's cache will only be invalidated if requirements.txt changes.
COPY requirements.txt .

# Install dependencies.
# --no-cache-dir prevents pip from storing its cache within this layer, reducing size.
# The '&& rm -rf ~/.cache/pip' cleans up any residual pip cache files after installation.
RUN pip install --no-cache-dir -r requirements.txt \
    && rm -rf ~/.cache/pip


COPY . .


EXPOSE 5000

# Run the app directly using the python interpreter
CMD ["python", "app.py"]
